      - name: Build deb
        run: |
          rm -rf pkg
          mkdir -p pkg/DEBIAN
          mkdir -p pkg/usr

          # Copy package payload
          cp -r usr/* pkg/usr/

          # Copy control files
          cp -r DEBIAN/* pkg/DEBIAN/

          # Fix required permissions
          chmod 755 pkg/DEBIAN
          chmod 644 pkg/DEBIAN/control
          chmod 755 pkg/usr/bin/apk-installer

          # Build deb properly
          dpkg-deb --root-owner-group --build pkg apk-installer.deb
