name: Build DEB

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build deb
        run: |
          rm -rf pkg
          mkdir -p pkg
          cp -r DEBIAN usr pkg/
          dpkg-deb --build pkg apk-installer.deb

      - uses: actions/upload-artifact@v4
        with:
          name: apk-installer
          path: apk-installer.deb
